services:
  ardupilot-sil:
    build:
      context: .
      dockerfile: ardupilot-sil.Dockerfile

    container_name: ardupilot-sil
    ports:
    - 15760-16000:5760-6000
    restart: 'always'
    environment:
    - COUNT=${NUMCOPTERS:-3}
